public with sharing class DebugClass {
    public void debugMethod() {
                    String s = 'Welcome to BJIT';       
        System.debug(S);
        Decimal num = 123.456;
        System.debug(num);
        Date dt = Date.today();
        System.debug(dt);

        Datetime dtt = daTetiMe.now();
        System.debug(dtt);
    }
    public DebugClass() {
           System.debug('***** DebugClass()');
    }
}